server:
  port: 0 # random port number setting

spring:
  application:
    name: user-service

eureka:
  instance: # eureka 에서는 처음 설정한 0으로 나오기 때문에 겹쳐서 보임 -> id 지정 필요
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true # EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 설정
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
